---
deployment:
  tasks:
    - |
      /bin/bash <<'DEPLOY'
      set -euo pipefail

      # ------------------------------------------------------------------
      # FactuFast cPanel deployment helper
      # ------------------------------------------------------------------
      : "${ACCOUNT_HOME:=$HOME}"
      : "${REPO_ROOT:=$(pwd)}"
      : "${DEPLOY_ENV_FILE:=$REPO_ROOT/deploy/.deploy-env}"

      if [ -f "$DEPLOY_ENV_FILE" ]; then
        printf '\nLoading deployment overrides from %s\n\n' "$DEPLOY_ENV_FILE"
        set -a
        # shellcheck disable=SC1090
        source "$DEPLOY_ENV_FILE"
        set +a
      fi

      : "${PUBLIC_HTML:=$ACCOUNT_HOME/public_html}"
      API_DIR="$REPO_ROOT/api"
      SITE_DIR="$REPO_ROOT/site"

      : "${PHP_BIN:=php}"
      : "${COMPOSER_BIN:=composer}"
      : "${NODE_BIN:=node}"
      : "${NPM_BIN:=npm}"

      log()  { printf '\n[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

      section() {
        printf '\n============================================================\n'
        printf '%s\n' "$*"
        printf '============================================================\n\n'
      }

      ensure_directory() {
        if [ ! -d "$1" ]; then
          mkdir -p "$1"
        fi
      }

      section "Installing Laravel dependencies"
      cd "$API_DIR"

      if [ ! -f composer.lock ]; then
        log "composer.lock not found; generating via composer install"
      fi

      $COMPOSER_BIN install --no-dev --optimize-autoloader --prefer-dist

      if [ ! -f .env ]; then
        log "No .env found; copying from .env.example (remember to edit the credentials!)"
        cp .env.example .env
        $PHP_BIN artisan key:generate --force
      fi

      log "Updating storage symlink"
      $PHP_BIN artisan storage:link || true

      log "Setting storage/bootstrap permissions"
      find storage -type d -exec chmod 775 {} \;
      find storage -type f -exec chmod 664 {} \;
      find bootstrap/cache -type d -exec chmod 775 {} \;
      find bootstrap/cache -type f -exec chmod 664 {} \;

      section "Migrating database"
      $PHP_BIN artisan migrate --force

      section "Caching Laravel configuration"
      $PHP_BIN artisan config:cache
      $PHP_BIN artisan route:cache
      $PHP_BIN artisan view:cache

      if [ -d "$SITE_DIR" ]; then
        section "Building Angular frontend"
        cd "$SITE_DIR"

        if [ -f package-lock.json ]; then
          $NPM_BIN ci
        else
          $NPM_BIN install
        fi

        $NPM_BIN run build -- --configuration=production

        section "Publishing Angular build to ${PUBLIC_HTML}"
        ensure_directory "$PUBLIC_HTML"

        rsync -a --delete "${SITE_DIR}/dist/site/browser/" "$PUBLIC_HTML/"
      else
        log "Angular site directory not found; skipping frontend build"
      fi

      section "Deployment completed successfully"
      DEPLOY
